mtreinish/stestr

- .gitignore
We don't need to track this in a git repository.
I'm not sure the ".stestr" is your intentional or not, though :)
> Add .stestr directory to .gitignore

- tox.ini
This commit adds py35 to tox.ini envlist. Because py35 is the default
python3 version in Ubuntu xenial.
> Add py35 to tox.ini envlist

- setup.cfg
This commit adds Python 3.5 support to setup.cfg. That version is
already included in tox.ini. So we can also add it to setup.cfg.
> Add Python 3.5 to setup.cfg

- stestr/test_listing_fixture.py
This commit fixes the concurrency option from str to int in the run
command. In python3, we need to make it convert to an int value,
explicitly. Otherwise, "TypeError: 'str' object cannot be interpreted as
an integer" error occurs.
> Fix concurrency option type to int

- doc/source/MANUAL.rst
This commit fixes some typos stestr. I think these "testr"s should be "stestr". And this commit also strip trailing white spaces.
> Fix typo to stestr

- .gitignore
This commit removes '/.testrepository' from .gitignore. We don't make
that directory anymore, so we don't need to ignore it.
> Remove /.testrepository from .gitignore

- doc/source/MANUAL.rst
- stestr/commands/run.py
- stestr/test_listing_fixture.py
- stestr/tests/test_return_codes.py
This commit adds a --serial option and removes the --parallel option
because it is already by default. And this commit also updates
MANUAL.rst for it.
resolve #13
> Add serial option to CLI

- stestr/commands/run.py
This commit removes 'LINEFEED' variable. We don't use this anymore.
> Remove LINEFEED variable

- stestr/commands/stats.py
This commit adds a line feed to stats command output. Otherwise, it is
ugly.
> Add line feed to stats command output

- stestr/commands/load.py
This commit removes an extra dash from force-init option of load
subcommand. Three dashes are too many for the option.
> Remove extra dash from force-init option of load

- doc/source/MANUAL.rst
- stestr/commands/run.py
- stestr/scheduler.py
- stestr/test_listing_fixture.py
- stestr/tests/test_scheduler.py
This commit adds a new option to randomize the test order. This is
useful because in certain situations you want to introduce a bit
of entropy into the execution order. When this option is used the
same scheduler test partitioning strategy is used, but before the
list of tests is passed to subunit.run for execution the list is
shuffled.
> Add CLI option to stestr run to randomize test order

- stestr/scheduler.py
- stestr/tests/test_scheduler.py
(I just updated the commit message with deleting and making the branch. I don't know how to do it without the tricky thing...)
This commit fixes the scheduler.partition_tests randomize option. I
noticed that 'out_parts.append(set(temp_part))' returns
[{'c_test', 'd_test'}, {'b_test', 'a_test'}]
but 'partitions' is
[['c_test', 'd_test'], ['b_test', 'a_test']]
(in python3).
However, we can't test it because it can be same as randomize=False in a
small chance. It might be rare, however unstable tests can be confusing.
> Fix scheduler.partition_tests randomize option

- stestr/cli.py
If no command is specified on the CLI return the help message
instead of showing a stack trace.
Fixes #35
> Return help message is no command is specified

- stestr/commands/run.py
- stestr/tests/test_return_codes.py
This commit fixes an error when `stestr run` with a bad regex.
Fixes #36
> Fix error stestr run with bad regex

- stestr/config_file.py
If you are running stestr and somehow end up in an
unexpected directory (for example when running within
an IDE) the config file may not be found, and the
test_path variable in stestr/config_file.py will
not be set, resulting in an exception. This patch
will check for a non-None value for test_path and
print a (hopefully) useful error message when
test_path isn't set.
> Print nice error message when test_path isn't set

- stestr/repository/sql.py
This commit fixes the wrong count condition in sql.py. The condition
always count it as success because
if test_dict['status'] == 'success' or 'xfail':
is always True.
Fixes: #41
> Fix wrong count condition in SQL

- stestr/config_file.py
- stestr/test_listing_fixture.py
- stestr/tests/test_config_file.py
- stestr/tests/test_test_listing_fixture.py
dbm_gnu library does not exist on Windows. Uses anydbm on
Windows instead.
Passing preexec_fn to Popen is not supported on Windows. Passes
None instead.
Makes the list command more Windows-friendly on Windows.
> Adds Windows support

- stestr/cli.py
This commit makes the version string full with vcs. It is used for
--version option. Sometimes I want to know more detailed version to know
the exact version what I'm using.
> Make version string return full string with vcs

- stestr/commands/load.py
- stestr/repository/abstract.py
- stestr/repository/file.py
- stestr/repository/memory.py
- stestr/repository/sql.py
This conmmit adds suport to the stestr load command and the underlying
repository API to append a stream into an existing entry in the DB. In
the repository API this is accomplished by adding a new optional
argument on the _get_inserter Abstract repository class to specify a
run_id. When specified the inserter returned will be for that already
existing entry in the repository. The stestr load command just leverages
this new mechanism by taking an id field on the cli and passing it to
the invocation of get_inserter.
> Add support to stestr load to append to an existing entry

- .coveragerc
- .gitignore
- tox.ini
This commit enables to get coverage with tox. We probably should care
about unit test coverage data of stestr a bit :)
> Enable coverage with tox

- .travis.yml
This commit adds 'cover' task to the tox envlist to enable coveralls
job.
> Add cover to tox envlist to enable coveralls

- README.rst
This commit adds build status badges - TravisCI and Coveralls. This
could be useful to see the build status and coverage rate of stestr.
> Add build status and coverage badges

- .coveragerc
- tox.ini
This commit improves to collect more coverage data. According to the
coverage.py document[1], we need some tricks to measure sub-processes
coverage. So, this commit is trying to do it.
[1] http://coverage.readthedocs.io/en/coverage-4.2/subprocess.html
> Improve coverage collection

- stestr/selection.py
This commit removes some code which is never called for printing skips
during selection.
> Remove unused code for printing skips

- stestr/commands/run.py
- stestr/config_file.py
This commit cleans up the error handling for when stestr run is called
without a repository and no config file or test-path arg is specified.
This is very common for new users to go to a directory with tests and
run 'stestr run' not having read the README or manual. Previously if
this was done you'd be greated by a repository not found traceback which
is hardly helpful. This cleans it up so a message prints explaing what's
missing and exits with an error code. As commit also cleans up the
wording for the error message when the same mistake is made with a
pre-existing repository.
> Cleanup error handling for missing test-path or config file

- README.rst
This commit adds two badges of codeclimate[1] and pypi version[2]. This
might be useful for healthy code and to know the latest version of
stestr.
[1] https://codeclimate.com/github/mtreinish/stestr
[2] https://pypi.python.org/pypi/stestr
> Add codeclimate and pypi version badges

- stestr/output.py
- stestr/test_listing_fixture.py
The test listing fixture had some leftover output straight from testr
which can be confusing. First is it prints the subprocess commands that
were being run, which is unecessary and confusing if you don't know what
is going in on internally. Secondly when it encounters an import it
raises an unhandled exception to crash. This commit fixes this by
printing out a more detailed view of what happened with an explanation.
Also a leftover failure condition from testrepository was removed
because it can never be tripped in stestr.
> Cleanup output from test listing fixture

- doc/source/MANUAL.rst
- stestr/commands/load.py
- stestr/commands/run.py
- stestr/tests/test_return_codes.py
This commit adds a cli flag to stestr run to append the results of the
run to the latest run in the repository. This is useful if you're
splitting the execution of a test suite over multiple invocations of
stestr run.
> Add combine option to stestr run

- .travis.yml
- .travis/coveralls.sh
This commit makes to get coverage only one time in travis-ci. We don't
need to get coverages for every python environment and pep8 task.
Fixes #59
> Get coverage only one time in travis-ci

- doc/source/MANUAL.rst
- stestr/scheduler.py
- stestr/test_listing_fixture.py
- stestr/tests/test_scheduler.py
This commit adds a new option in the manual scheduler yaml syntax. There
are certain situations where you want to treat a subset of tests being
manually scheduled like the default case with the standard test
scheduling mechanisms. To enable doing this a 'concurrency' field can be
used on a worker, and tests on those workers will be scheduled like
normal across the number of workers specified.
> Add a concurrency option to the manual scheduler

- stestr/repository/sql.py
Previously the subunit2sql-db-manage command is called via subprocess
call() function. This mean that the stdout and stderr from that command
was being missed by the stdout and stderr fixtures because it wasn't
originating from the parent process. This commit fixes this by storing
the stdout and stderr in a subprocess.PIPE and writing it to the parent
process's stdout and stderr at the end of the execution.
> Write subunit2sql db manage output to local stdout

- stestr/commands/failing.py
- stestr/commands/init.py
- stestr/commands/last.py
- stestr/commands/list.py
- stestr/commands/load.py
- stestr/commands/run.py
- stestr/commands/slowest.py
- stestr/commands/stats.py
- stestr/config_file.py
- stestr/test_listing_fixture.py
- stestr/tests/test_config_file.py
This commit adds a real api for running the stestr commands. Instead of just having a magic run() function that takes in an tuple of a argparse Namespace and a list of undefined arguments this migrates all the real work into a function that has properly defined kwargs. The run() command is then relegated to just convert the Namespace into a dict and pass the arguments into that real function. This enables external programs to just call the new functions with defined args and run commands exactly like on the cli, but with a defined python interface. It makes everything a lot easier for python consumption. The tradeoff here though is that everything is bit more verbose, but that's the cost of being explicit with a defined interface.
As a side effect of this change instead of passing that …
> Add python interface for commands

- stestr/config_file.py
This commit fixes a small bug in the recent python api change that
causes the --test-path argument to not work. The if condition for
determining if a test_path is not set in either the config file or the
cli was mistakenly assuming if it was set on the cli was the same as not
being set. This commit fixes it by explictly checking if it's not set.
> Fix stestr --test-path argument for stestr run and list

- stestr/config_file.py
- stestr/test_processor.py
- stestr/tests/test_config_file.py
- stestr/tests/test_test_processor.py
The name test_listing_fixture was a bit confusing. It was a hold over
from test_repository that was never renamed. Even in testrepository the
function of the module is much more than simply listing tests. It's
where all the test workers are launched. While if you look at the
internals of the module the life of the fixture is around the temporary
test list files it creates. But, this name is confusing for people not
super familiar with the internals.
To try and clear up any potential confusion here this commit renames it
to the more generic 'test_processor' (and the Fixture class inside).
This hopefully makes it more clear that the role of the module is around
processing the tests, and more than just listing things.
Closes Issue #21
> Rename the test_listing_fixture to test_processor

- stestr/commands/run.py
- stestr/tests/test_return_codes.py
The --subunit flag on stestr run, load, etc always returns 0. This is
done primarily to ensure that subunit processing can happen without
issue, especially from inside a python caller. (there is also an implicit
assumption that if you emit subunit whatever consumes that will check
for the failure condition and handle that itself) This has a side effect
for the --until-failure flag on stestr run which will never exit if
--subunit is used because there is never a failure condition detected
because subunit output always returns 0. This commit fixes this by
checking the repository directly for failure if --subunit and
--until-failure are used together.
Closes Issue #68
> Fix stestr run --until-failure with subunit output

- doc/source/api.rst
- doc/source/api/commands/failing.rst
- doc/source/api/commands/init.rst
- doc/source/api/commands/last.rst
- doc/source/api/commands/list.rst
- doc/source/api/commands/load.rst
- doc/source/api/commands/run.rst
- doc/source/api/commands/slowest.rst
- doc/source/internal_arch.rst
- stestr/commands/failing.py
- stestr/commands/init.py
- stestr/commands/last.py
- stestr/commands/load.py
- stestr/commands/run.py
- stestr/commands/slowest.py
This commit adds api documentation for the commands modules in
preparation for the next release. These modules wil lbe considered a
stable interface moving forward, so we want to have documentation for
their use.
> Add API docs for the commands

- stestr/commands/failing.py
- stestr/commands/last.py
- stestr/commands/list.py
- stestr/commands/load.py
- stestr/commands/run.py
- stestr/commands/slowest.py
- stestr/tests/test_return_codes.py
This commit adds a stdout argument to the command functions. If you're
calling a command function from python there are several use cases where
you don't want the output to unconditionally go to stdout. To enable
such use cases this commit adds a stdout arg to all the functions that
write to stdout. By default sys.stdout will be used as before, but any
file object can be used instead.
A bugfix commit is tacked on to the end here, because I found it during the refactor.
> Add stdout param

- stestr/commands/init.py
Previously if you ran stestr init with a file type repo on a path where
the repository already created you would get a stack trace. That's
because the file layer will go to do a mkdir and if the path already
exists it will raise an exception which bubbles up to the cli layer.
This commit just catches the FileExistsError and prints a message
instead.
> Handle stestr init with existing path

- .travis/coveralls.sh
This commit fixes a small typo in the coveralls run script. We haven't
been aggregating coverage data since late May. It looks like this is
because the script to call coveralls was running the coverall command,
but according to the docs this should be coveralls.
> Fix coveralls collection

- CODE_OF_CONDUCT.md
Github was bugging me about adding a code of conduct to the repository and I actually think it's a good idea. Despite having very few contributors to this project and a small community around it. If it ever grows or there is a problem having a code of conduct written down will at least set the expectations just in case.
> Create a Code of Conduct for the project

- stestr/repository/file.py
- stestr/selection.py
- stestr/test_processor.py
- stestr/tests/repository/test_file.py
- stestr/tests/test_return_codes.py
- tools/testr_to_stestr.py
This commit tries to use context managers for file open(). In the
previous commit, it already has been done as a bug fix. However, these
also can be fixed to close files. In some cases, the original code are
not harmful, but I changed it to keep the code clean.
> Use context managers for file open()

- setup.cfg
The trove classifiers for stestr are a bit inaccurate, mostly because I
copy and pasted the original setup.cfg from another project. This commit
updates the classifiers in the setup.cfg to better reflect reality.
> Update the trove classifiers

- stestr/commands/last.py
This commit makes to print just the error message without a stacktrace
when no stestr repository or no test run. We don't need to show a
stacktrace like this predictable situation.
Closes Issue #88
> Print just error message when no stestr repo

- stestr/commands/run.py
In the stestr run command the whitelist arg is passed to the inner
function, but on all the calls to get_run_command() we neglected to pass
the whitelist arg to that function. This commit fixes this by passing
the whitelist arg down to the lower levels.
Fixes issue #92
> Fix whitelist arg usage in stestr run

- doc/source/MANUAL.rst
The manual was missing the run command for a bunch of examples in the
docs. This commit fixes that.
> Add missing run command to stestr manual

- doc/source/MANUAL.rst
- stestr/commands/load.py
- stestr/commands/run.py
This commit adds a new flag to the stestr run and load comands for
printing abbreviated output. By default the full subunit-trace output is
used, but in some cases this is overly verbose. To enable a tradeoff
between the full verbosity and the blank output during execution this
flag will print a single character as each test executes.
> Add a --abbreviate flag to stestr run and load

- stestr/commands/load.py
The if logic in stestr load was incorrect and when subunit_out was
specified it would set the right variables, but then override them later
in the code path. This commit fixes it so that when subunit_out is used
those settings hold true until the actual stream is run. In the process
another bug was fixed when subunit_out and pretty_out were both set the
subunit_trace summary was still printed because of a similar if logic
issue.
Closes Issue #101
> Fix if logic on output types in stestr load

- tools/testr_to_stestr.py
Apparently if -t is not specified, the path to the unit test directory
follows immediately the "discover" keyword.
This change was applied to and tested against the similar code inside
ostestr which parses and coverts .testr.conf on the fly:
https://review.openstack.org/503877/
> Fix .testr.conf parsing: test path follows discover

- stestr/test_processor.py
- stestr/tests/test_return_codes.py
When test_processor is doing it's initial test_id list generation it has
to determine whether or not discovery is necessary. Whenever a dynamic
test selection mechanism (regex, black regex, whitelist, or blacklist)
is used running discovery is necessary if test_ids aren't supplied.
However, the check for this only understood the normal regex and wasn't
checking if any of the other selection mechanisms were in use. This
commit fixes this issue by checking if any of the selection mechanisms
are in use instead of just a regex.
Fixes issue #103
> Respect all selection mechanisms for discovery check

- stestr/commands/load.py
- stestr/tests/test_return_codes.py
This commit fixes a bug in stestr load when passing in a subunit stream
from stdin. It was previously trying to read the stream form the stdin
buffer, but that doesn't always (and in most cases) exist. It turns out
there was no need to do this, so this commit just fixes that by using
the stdin object itself.
Fixes #109
> Fix stestr load from stdin

- stestr/bisect_tests.py
- stestr/commands/run.py
The analyze-isolation command was never update after the stestr repo was
forked from testrepository. This code path was still making a bunch of
calls assuming the repo was still laid out like testrepository. This
commit fixes all of these and refactors the test biscet code to live in
it's own class. This also adds tests for this logic to ensure it works.
As it is now this feature will only discover conflicts between tests in
the same process, since it relies in the order of execution on a specific
worker.
More unit tests are needed to fully cover this feature.
> Fix the stestr run --analyze-isolation flag

- doc/source/developer_guidelines.rst
We haven't really ever used reno for handling release notes, and we
recently removed the releasenotes section from the tree. This commit
just cleans up a stray doc that was telling people to use reno.
> Remove contributor docs for using reno

- stestr/commands/load.py
The stestr load command was not passing the stdout arg to the
make_result call, which is what we use to generate the subunit output.
This commit fixes this oversight and passing stdout to the function to
make sure we write the subunit output to the specified file instead of
unconditionally using sys.stdout.
Fixes Issue #115
> Pass output to output.make_result() in stestr load

- .travis.yml
This commit makes some updates to the travis config to better reflect
the current state of things. First it removes the python 3.4 testing.
Most people are running this on python 3.5 or 3.6 if they're using
python3. (3.4.2 was released 3 years ago) We also don't advertise 3.4
support in the trove classifiers so there isn't any value in testing
that too. The other thing this patch does is update the non unit test
jobs to use 3.6 instead of 3.5. Since 3.6 is the latest version of
python we support we should be using that instead of 3.5.
> Update travis job config

- tools/find_and_rm.py
- tox.ini
This commit add a removing *.pyc files command before running stestr in
tox. Sometimes, old *.pyc files are remaining. It is not good,
basically.
> Remove pyc files before running stestr in tox

- stestr/cli.py
This commit makes to allow to use both group_regex and group-regex as an
optional argument. In all of optional arguments except this one, we use
a '-' to connect words. To keep the backward compatibility and
consistency, this commit allows both of optional arguments.
> Allow both group_regex and group-regex as an optional argument

- stestr/commands/load.py
- stestr/commands/run.py
- stestr/repository/abstract.py
The partial flag is vestigial and left over from the original testr fork.
It was originally used to indicate a run did not execute the entire test
suite. However this doesn't really come into play anywhere else and
it's not stored in the repository either. I think the eventual intent
was to treat those records as incomplete for other purposes but that
never really was implemented. With the introduction of load to run-id
and also a run --combine this isn't really needed anymore either. It's not
really something that should be user facing either. The user shouldn't
have to tell the runner whether the run is the full suite or not.
This commit removes the functional bits from the cli (and their python
api commands) and deprecates all the flags for partial. The repository
partial usage remains …
> Deprecate the partial flag

- stestr/commands/load.py
- stestr/commands/run.py
- stestr/results.py
- stestr/tests/test_return_codes.py
This commit makes run and load commands use the quiet option. We don't
need outputs of run and load commands occasionally. So, this patch adds
the function to suppress the outputs.
We already have the quiet option, however it isn't used so far. It might
be better to move the quiet (or silent) option to load and run commands
because the option doesn't work in the other commands now.
Fixes issue #121
> Implement quiet option for run and load commands

- stestr/commands/list.py
argparse returns an empty array for any unknown arguments; detect
this situation and default filters to None in this instance as
already performed in the 'run' cli module.
> list: Deal with [] instead of 'None' for filters

- stestr/commands/slowest.py
- stestr/tests/test_slowest.py
To calculate a starting point for the column width for printing the
slowest tests table the first result was pulled from the list of test
times and the number of digits was counted. However, in the case of a
0 or negative number this doesn't work because taking a base 10 log of
that will fail. This commit address this corner case by using the first
value > 0 and if none can be found defaulting to 1 digit.
> Handle zero and negative times in stestr slowest

- stestr/commands/run.py
ostestr provided a --slowest option that made it easy to get
a list of the slowest tests run. This is still possible with
`stestr slowest`, but there are cases where it would be more
convenient to have this automatically printed out without the
need of a separate command call.
This patch adds a --slowest option to the run, defaulted to
False, that will perform the slowest test output as part of
the run command.
> Add --slowest option to test runs

- doc/source/MANUAL.rst
- doc/source/api.rst
- doc/source/api/test_processor.rst
- doc/source/index.rst
This commit fixes some typos in the docs. And this commit removes
'search' link on the index page because the page isn't rendered on the
readthedocs page[0] and we can search the docs with the search box on
the left side on every page.
[0] http://stestr.readthedocs.io/en/latest/search.html
> Fix typos in docs

- stestr/subunit_trace.py
This subunit_trace.py was copied from os_testr[0] which has
"subunit_trace" command in it. However, stestr doesn't have that
command. So the shebang and execution bit aren't necessary. So, this
commit just removes them to keep the code simple and clean.
> Remove unnecessary shebang and execution bit from subunit_trace

- README.rst
This commit adds a badge for Appveyor status. Appveyor CI status is
important for stestr. So it should be good to have it on README.
> Add badge for Appveyor status

- doc/source/api.rst
- doc/source/internal_arch.rst
- requirements.txt
- setup.cfg
- stestr/cli.py
- stestr/commands/failing.py
- stestr/commands/init.py
- stestr/commands/last.py
- stestr/commands/list.py
- stestr/commands/load.py
- stestr/commands/run.py
- stestr/commands/slowest.py
- stestr/tests/test_return_codes.py
This commit makes stestr use cliff[1] for CLI layer. The cliff project
provides a lot of advantages for stestr cli which has subcommands.
Instead of just using argparse, we should leverage cliff to provide a
more plished CLI experience.
[1] https://pypi.python.org/pypi/cliff
Closes Issue #62
> Use cliff for CLI layer

- stestr/subunit_trace.py
This commit fixes a small oversight in a warning message from
subunit-trace where a worker tag is not found in the output stream. This
originally was added to subunit-trace to expose a race in testrepository.
However attributing this error to testr here has 2 issues, first that
particular bug has been fixed in testrepository and the error can't ever
come from  testr in the stestr embedded copy of subunit-trace. This
attepmts to make the warning message a bit clearer if anyone ever
encounters it from stestr.
> Fix warning message about missing worker tags in subunit-trace

- doc/source/MANUAL.rst
- requirements.txt
- stestr/cli.py
- stestr/commands/failing.py
- stestr/commands/last.py
- stestr/commands/load.py
- stestr/commands/run.py
- stestr/tests/test_user_config.py
- stestr/user_config.py
This commit adds a new feature, the user config file. This enables users
to write a global config file for UI preferences on certain commands
that will be the new default for that option. For example, if you prefer
the default output on the 'stestr run' command to be with the
--no-subunit-trace flag set. You can just write a user config file to
set this output. Then for all stestr run invocations the default output
will be with --no-subunit-trace set.
> Add support for a user config file

- stestr/commands/run.py
- stestr/tests/test_return_codes.py
This commit fixes the issue "no attribute `repo_type` error when
running with `--slowest` option. We have neither `repo_type` nor
`repo_url` in `args` but `self.app_args`.
Fixes Issue #140
> Fix no attribute 'repo_type' error when running w/ --slowest option

- stestr/tests/test_return_codes.py
- stestr/tests/test_user_config.py
- stestr/tests/test_user_config_return_codes.py
- stestr/user_config.py
This commit adds additional testing to cover the newly added user config
file feature from #139. This includes various permutations of CLI and
config file options to test for the correct operational behavior. This
testing managed to uncover a bug with empty config files which was
fixed.
One outstanding issue is the load abbreviated output option which
doesn't fully function. The abbreviated output (ie the '....') doesn't
get displayed, other than that it's fully functional. I assume this is a
bug in the subunit_trace module, so for now those 2 tests are skipped.
> Add functional tests for user config file

- setup.cfg
This commit updates the description of the stestr package. The one in
setup.cfg is quite old back from when we were still deciding on the
scope of the project. We have since updated the descriptions everywhere
else to explain the scope of the project. The setup.cfg summary is what
gets sent to pypi: https://pypi.python.org/pypi/stestr/2.0.0 so we
should update this to make sure it reflects the current scope of the
project more accurately.
> Update the package summary in setup.cfg metadata

- doc/source/MANUAL.rst
This commit fixes a small oversight in the stestr manual around test
selection. Previously it incorrectly said you use --list/-l to run a
test list, which isn't actually a thing in stestr. (I assume it was a
copy and paste error from ostestr) This really should read use stestr
list, which this commit does.
> Fix a small mistake in manual about test selection

- doc/source/MANUAL.rst
This commit fixes typos about ``--whitelist-file/--blacklist-file``
option in MANUAL.rst. We don't have snake case options such as
``--whitelist_file/--blacklist_file`` like below. This might come from ostestr
which supports both options.
```
$ stestr list --whitelist_file whitelist.txt
usage: stestr list [-h] [--blacklist-file BLACKLIST_FILE]
[--whitelist-file WHITELIST_FILE]
[--black-regex BLACK_REGEX]
[filters [filters ...]]
stestr list: error: unrecognized arguments: --whitelist_file
```
> Fix typos about whitelist/blacklist option in manual

- README.rst
This commit makes flat-square design badges on README. Since using
that design keeps this project latest.
I prefer the flat-square to the default ones because it's simpler.
> Use flat-square design badges on README

- README.rst
This commit adds alt texts for the badges in README. This would be
useful when the images can't be shown due to such as network issues, on a text browser, etc.
> Add alt texts for badges in README

- README.rst
The stestr README used to include a previous link to the stestr manual
page. This was done using sphinx internal refs, because in a
sphinx doc build this is the cleanest way. However, on github the README
is not rendered using sphinx, it just parses the rst directly and
converts that to html. This means we would have a link that didn't work.
To fix the rendered html output on github this changes that link to just
be an http link to the read the docs page for the stestr manual.
> Fix the manual docs link in README

- doc/source/MANUAL.rst
- doc/source/conf.py
This commit leverages the cliff autoprogram documentation sphinx to add
usage sections for each command to the beginning of the stestr manual.
This is a standard thing to list out each option in the cli which we
were missing from the docs. Luckily cliff provides an interface to
generate this so we don't have to write it out manually.
> Add usage to manual docs page

- .github/issue_template.md
While most of the bugs have been filed by the project maintainers it
still good to provide a template on some commonly needed information to
triage bugs. Especially including a note about --debug which is needed
to capture tracebacks.
> Add an issue template to project

- doc/source/conf.py
When using sphinx to generate a man page for stestr it was building a
man page out of all the docs in stestr. This worked fine but made a
pretty bad man page. The MANUAL.rst file is meant to be both an HTML
manual for using stestr and also would make a good man page. This commit
adjusts the root doc for manpage generation to be MANUAL.rst instead of
index.rst. This results in a much more sane manpage when running a
command like:
sphinx-build -b man doc/source doc/build/man
> Fix manpage generation

- requirements.txt
- setup.py
The PBR 4.0.0 release introduced a regression for windows .exe
generation [1]. This breaks the CI jobs in appveyor to verify things
still work on windows. To resolve this issue until there is a working
pbr release this commit caps the version we use to be < 4.0.0.
[1] https://bugs.launchpad.net/pbr/+bug/1761134
> Cap PBR<4.0.0

- doc/source/MANUAL.rst
- stestr/commands/last.py
- stestr/commands/load.py
- stestr/commands/run.py
- stestr/subunit_trace.py
- stestr/tests/test_user_config.py
- stestr/user_config.py
This commit adds a new cli and user_config option to suppress printing
attachments on successful test runs. Originally in subunit_trace stdout
and stderr were unconditionally printed on test success because the
theory was this was expected to be inadvertent and likely a bug so end
users would want to know if their tests were writing to to either
stream. However, this was a faulty assumption in that some test suites
write to either during normal operation and writing the contents on test
success is just polluting the output of a test run. Therefore this adds
an option to let the user configure this functionality to address that
use case.
> Add option to suppress attachment printing on successful tests

- stestr/tests/test_return_codes.py
This commit adds unit tests calling the command functions from the
python interface to verify their return codes. As things start to
consume the python interfaces it will be good to point to tests that
validate the return codes and functionality are the same as running from
the CLI. The tests added here are just a mirror of our cli return code
tests but instead of using subprocess they call the python api.
> Add unit tests for return code from functions

- doc/source/MANUAL.rst
We recently added a new option --suppress-attachments to stestr run, but
the patch that added it neglected to include documentation in the stestr
manual. This commit fixes that oversight and documents the flag.
> Add documentation for --suppress-attachments option

- .appveyor.yml
Running pip>=10.0.0 in the windows ci is failing and blocking changes.
This commit is to workaround this issue, #165, until the upstream
pypa/pip#5223 (or equivalent bug) is fixed in another pip release by
capping pip to be <10.0.0.
> Cap pip version in windows ci

- stestr/tests/test_return_codes.py
This commit is an attempt to mitigate #162 where the temp directory
removal is failing on windows CI occasionally. This commit sets the
ignore_errors flag on the shutil.rmtree() call which makes any errors
encountered not fatal. While this isn't ideal because it could result
in leaking the temp directories on test runs. But, since we haven't
encountered this failure on any operating system or environment
besides the windows CI in appveyor the risk of that weighed against
the nondeterministic failures blocking changes minimizes that concern.
> Ignore errors on cleanup in test_return_codes

- stestr/commands/run.py
This commit fixes to be able to specify `abbreviate` option from not
only a user config file but also a command line. We should be able to
switch the flag from a command line.
> Fix abbreviate option in run subcommand

- doc/source/MANUAL.rst
The manpage section on configuring stestr was referring to a
non-existent help text to get the contents of a full config file. This
commit fixes this and cleans some other pieces up and adds more details
where needed.
> Cleanup manual section on configuration

- README.rst
- doc/source/MANUAL.rst
- doc/source/internal_arch.rst
This commit makes the URLs of the python docs switch from version 2 to
version 3. We should point to the latest version documents as
possible if there is no particular reason.
> Switch python doc reference from 2 to 3

- stestr/output.py
This commit removes the code for Python 2.6 version. We don't test
stestr on Python 2.6 and we also declare the versions only 3.6, 3.5
and 2.7 in setup.cfg. So, we don't need to have this code anymore.
> Remove Python 2.6 code

- doc/source/MANUAL.rst
Interpreting the manual section about Grouping Tests required
remembering that match() only matches at the start of a string; and that
group(0) is the entire matching portion of the regex, not the first
group. State this explicitly instead.
> Clarify docs on group_regex

- .appveyor.yml
Reverts mtreinish/stestr#166
The latest pip version is supposed to have fixed this, so let's remove the cap.
Closes #165
> Revert "Cap pip version in windows ci"

- requirements.txt
- setup.py
The previous commit attempted to uncap pbr to see if the windows issue
was addressed. But neglected to do so in the setup.py cap in addition to
the requirements file. This commit corrects the oversight and uncaps
that too.
> Really uncap pbr

- stestr/commands/run.py
The description for the run command being returned by the
get_description() function was truncated because the string was split
over multiple lines. However, the split was done incorrectly and the
second part wasn't being set. This commit corrects the oversight so the
description is complete in the documentation and --help.
> Fix description for the stestr run command

- stestr/commands/load.py
During the migration to cliff for the 2.0.0 release we accidentally
swapped the description for some arguments to the load command. This
commit corrects this and corrects the help text for all the arguments.
> Cleanup argument help text on load command

- stestr/selection.py
- stestr/tests/test_selection.py
This commit adds error handling for invalid input regexes on any of the
test selection mechanisms. Now when an invalid regex is encountered an
error message will be printed and then stestr will exit. This should hopefully
make it easier to identify bad user input, like described in #181.
The logic in selection.py needed to be reworked slightly to
differentiate between invalid regex in input filters and the whitelist
file.
> Add error handling for invalid input regexes

- stestr/commands/failing.py
- stestr/commands/last.py
- stestr/commands/load.py
- stestr/commands/run.py
- stestr/results.py
- stestr/subunit_trace.py
- stestr/tests/files/failing-tests
- stestr/tests/files/passing-tests
- stestr/tests/test_return_codes.py
This commit addresses a bug when unexpected success results are used
by a test suite. stestr was relying on wasSuccessful() method in the
StreamResult class from testtools, which doesn't properly account for
unexpected success. So when stestr was run on a test suite it wouldn't
properly handle tests with unexpected success result and thus treat
the run as successful. This addresses the issue by adjusting our
testtools api usage to call the wasSuccessful() method from the
TestResult class instead which has the correct behavior.
An issue has been opened in testtools testing-cabal/testtools#273
regarding the accounting error with StreamResult.wasSuccessful(),
if/when a fix is introduced into a released testtools we can investigate
switching these calls back to use that function. But for the …
> Fix handling of unexpected success results

- doc/source/MANUAL.rst
- stestr/commands/run.py
- stestr/tests/test_return_codes.py
This commit adds support to the --no-discover/-n flag on stestr run for
specifying a test class and test method when passing in a filepath. This
borrows the syntax from pytest so you use '::' to specify a class and
then method. For example 'path/test_mod.py::TestClassA::test_method_b'
would be used to run only test_method_b in the TestClassA test case in
the path/test_mod.py file.
Fixes #180
> Add support for test class and method by path on no-discover

- stestr/commands/load.py
- stestr/subunit_trace.py
This commit updates the subunit_trace module to leverage the timestamps
reported in the subunit instead of the wall time for the elapsed time
output. When we were using the wall time if we were just reading a
subunit file this would be the time it took to read an process the
subunit data. Which is not the actual run time of the test. By switching
to use the elapsed time between the first start timestamp and the last
stop timestamp we'll always get an accurate value. This does come with
the tradeoff of not counting any setUp before the start time or
tearDown/cleanUp after the last test, since that data isn't in the
subunit stream. But that feels like a worthwhile compromise for having
moderately accurate numbers all the time.
Fixes #119
> Use reported times instead of wall time in subunit-trace

- stestr/commands/load.py
This commit tries to fix the issue #137 "WARNING: missing Worker N!"
when using `stsetr run --failing` / `stestr load ..`.
We shouldn't use `testtools.ConcurrentStreamTestSuite` when we load
past subunit data. Because it doesn't match the load workers against
the run workers.
Fixes #137
> Make test running serially when just loading

- stestr/bisect_tests.py
- stestr/commands/run.py
- stestr/tests/test_bisect_return_codes.py
This commit just removes unused parameters - `failing`,
`analyze_isolation`, `isolated` from `_run_tests()` and its
usages. I'm not sure we have a plan to use the parameters in the
future, but we don't need them and a bit confusing at least so far.
And also, this commit adds a linefeed to the assert message to make
it better.
> Cleanup unused parameters in _run_tests

- README.rst
This commit adds some text to the README's overview section. Previously
it didn't actually directly say what stestr was, it just starts talking
about being a fork of testr. This cleans this up by describing what
stestr is and how it works before talking about it being a fork of
testr.
> Add a better description to README Overview section

- stestr/test_processor.py
This commit fixes the formatting when we print the errors encountered
during discovery. Because python3 returns a bytes object from subprocess
just casting it as a str() won't make the ouptut respect the the
newlines and tabs. To fix the issue this commit splits out the py3 case
and properly decodes the bytes as utf8 data and pass that to
sys.stdout.write().
> Fix discovery import error formatting on py3

- README.rst
No one calls stestr Slim Test Repository or Super Test Repository, so
lets stop referring to it as that. stestr should just be stestr, for
better or worse, and not stand for anything. This commit just updates
the readme to reflect this.
> Change title of project in readme

- doc/source/MANUAL.rst
- stestr/cli.py
- stestr/config_file.py
- stestr/tests/test_config_file.py
- stestr/tests/test_return_codes.py
This commit introduces the parallel-class option to the CLI and config
file. The option take priority over group_regex. And if both on the
CLI and in the config are set, we use the option on the CLI not in a
config file.
For example, `--group-regex` on the CLI and `parallel-class` in a
config file are set, `--group-regex` is higer priority than
`parallel-class` in this case.
Fixes #198
> Introduce parallel-class option

- stestr/cli.py
By default cliff suppresses stack traces on unhandled exceptions in order
to keep the output cleaner for users. But in practice this has caused more
confusion for stestr users since often the error messages aren't really
descriptive enough to indicate what's going wrong (or that it's even a
bug in stestr). This is often because exception messages are written
assuming the context of the stack trace for debugging, not to be user
facing messages. Cliff offers the --debug flag to enable printing the
full stack traces. This commit turns that flag on by default when stestr
initializes the cliff App object to ensure that it always prints the
full stack trace on an unhandled exception.
Fixes #220
> Turn on debug mode by default

- stestr/tests/test_bisect_return_codes.py
- stestr/tests/test_return_codes.py
This commit makes some unit tests use an empty user config file as a
default setting. Otherwise, it can be failed with user config settings
depending on a test user's user config.
And this commit also fixes `test_serial_subunit_passing` to have
`--serial` option for its objective.
> Use default user config in unit tests

- stestr/config_file.py
- stestr/tests/test_config_file.py
In case of top_dir and test_path contains a space, stestr fails.
Putting these variables in quotes fixes the problem.
Fix #211
> Put in quotes the top_dir and test_path

- stestr/tests/test_return_codes.py
stestr run --subunit always returns 0 exit status irrespective
of the tests passes or fail. It improves the test coverage for
the same.
It also fixes the test command for test_serial_subunit_passing.
> Improved test coverage for stestr run --subunit 0 exit status

- stestr/config_file.py
- stestr/tests/test_config_file.py
It may happen, even if it is extremely unlikely.
Just return 'python': it may work, or just fail later - but it would
have failed anyway.
This is a follow-up of the main fix for #215.
> Gracefully handle the case when sys.executable is None

- stestr/commands/run.py
This commit adds a detailed error message when a user passes in a
concurrency outside the expected range (which is >= 0). Previously
we'd raise an unhandled IndexError because of going outside the list
bounds deeper in the code, which wasn't super useful or informative for
users. This fixes that by detecting when we have an invalid input up
front and print that out before we run anything.
Related to: #202
> Add error message for invalid concurrency value

- stestr/commands/failing.py
- stestr/commands/last.py
- stestr/commands/load.py
- stestr/commands/run.py
The --subunit flag changes the exit code behavior in a slightly
counter intuitive manner. Basically instead of exiting non-zero when
there are failure results it only returns non-zero if subunit generation
fails. This is expected behavior, but was not clearly documented which
can cause confusion. It was only mentioned in the description for the
'last' command, and not all the commands where --subunit was available.
This commit attempts to address that by adding clear documentation to
the description string for each command. This means it will be printed
in the summary for '--help' on each command as well as ending up in the
project man page for each command.
Fixes #210
> Update docs for exit codes with --subunit flags

- stestr/commands/init.py
- stestr/commands/list.py
- stestr/commands/slowest.py
This commit moves help descriptions in the rest of the commands. We
found that in #214 conversation and fixed some already. But we decided
to make a separate PR for this fixing there.
Related Issue: #214
> Move from get_description() to class docstrings part-2

- README.rst
- setup.cfg
This commit adds the GitHub repo and readthedocs links to README.rst and
setup.cfg to try to make it easier to find it.
Issues #218
> Add links to GitHub repo and project-urls to metadata

- README.rst
- doc/source/CONTRIBUTING.rst
- doc/source/index.rst
We have had a CONTRIBUTING.rst file in the repo for some time (at the
suggestion of Github) but this is not discoverable unless you can find
the repo. As pointed out in issue #218 the repo can be hard to find in
certain cases, so this document isn't always discoverable. In an effort
to fix this, this commit updates the README to include this content.
Additionally it adds the CONTRIBUTING.rst file to the rendered docs.
Fixes #218
> Inline CONTRIBUTING.rst in README.rst and add to docs

- stestr/commands/run.py
- stestr/tests/test_run.py
This commit fixes `concurrency is None` case. The original code was
taking care of ValueError case such as 'foo', but if we pass `None` to
the `_to_int()`, it raised a TypeError. So, this commit converts it to a
ValueError instead.
> Take care of 'concurrency is None' case

- stestr/scheduler.py
- stestr/tests/test_scheduler.py
- stestr/tests/test_user_config.py
- stestr/user_config.py
yaml.load(input) is deprecated from PyYAML 5.1[0]. Therefore, some
warnings are showed up in a stestr unit test case which causes a failure
in test_load_from_stdin_quiet() because it expects empty string.
This commit makes it to use yaml.safe_load instead of yaml.load. Because
it doesn't show the deprecation warnings.
[0] https://github.com/yaml/pyyaml/wiki/PyYAML-yaml.load(input)-Deprecation
Closes: #234
> Use yaml.safe_load instead of yaml.load

- doc/source/conf.py
This commit updates the copyright year in the document. It's better to
keep it up-to-date because it prevents people think stestr is stale or
dead with the documents.
> Update copyright year

- stestr/commands/run.py
Currently it's hardcoded to 'python' wich in some cases may not exist,
as in some distros with python3 only.
This patch uses PYTHON env variable if defined or executable used to run
stestr.
> Discover python executable when discover is not used

- stestr/repository/abstract.py
- stestr/repository/file.py
- stestr/repository/memory.py
- stestr/repository/sql.py
- stestr/tests/repository/test_file.py
- stestr/tests/repository/test_sql.py
This commit adds repository APIs around storing and accessing run
metadata strings. The concept being that you can store a metadata string
to identify a run by some other identifier then the run id. The example
use case in mind for this feature is using it to store a VCS commit hash
(like a git sha1) or identifier. The APIs in this commit allow storing
metadata at run creation time, accessing the metadata for a run, and
finding run_ids by a metadata value. This is implemented for both the
file and sql repository types. The memory repository type does not have
this implemented, as it is more limited.
Related to: #224
> Add support to repositories for storing run metadata

- test-requirements.txt
This commit caps and limits the sphinx version which causes errors.
Especially, the version from 2.0.0 is not compatible with python2.7.
We are planning to drop our support for python2.7 next year but we still
need to support it at this point.
> Cap sphinx version <2.0.0 when python2.7

- doc/source/MANUAL.rst
- stestr/commands/last.py
- stestr/commands/load.py
- stestr/commands/run.py
- stestr/subunit_trace.py
- stestr/tests/test_user_config.py
- stestr/user_config.py
This commit adds a new flag, --all-attachments, to the run, load, and
last commands (in addition to a matching user config flag). When set
this flag will tell subunit trace to print all text attachments for a
test whether it was successful or it failed.
Fixes #223
> Add flag to print all attachments for successful tests

- .travis.yml
- setup.cfg
This commit adds travis jobs on tag releases to build the release
artifacts for pypi. It will generate both an sdist and a universal
wheel and then upload that to pypi. This automates the release process
so that when it's release time we only need to push a tag to github
and everything else is handled automatically.
> Add release automation for pypi artifacts

- doc/source/MANUAL.rst
- stestr/commands/last.py
- stestr/commands/load.py
- stestr/commands/run.py
This commit reworks the logic for handling the 2 mutually exclusive
options suppress attachments and all attachments. Previosuly supress
attachments would always take precedence over all attachments, even if
all attachments were set via the cli and all attachments were in the
user config file. This commit makes the behavior more consistent with
expectations and has it so cli arguments always take precedence. It also
changes the behavior to error if both options are set on the cli.
> Rework logic for suppress attachments and all attachments

- README.rst
- stestr/cli.py
Now that we're getting ready to drop python 2 support for an stestr
3.0.0 release in early 2020 this commit adds a release note to make the
plans clear to end users.
> Add readme note about python 2 eol in readme

- azure-pipelines.yml
This commit adds a macOS Mojave(10.14) testing job strategy to the azure
pipelines. In the document[0], it supports macOS 10.14 and 10.13 but we
don't need to test all versions of macOS and Python. So, as a first
step, this commit just add one job.
[0] https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops#use-a-microsoft-hosted-agent
> Add macOS py37 azure pipelines

- stestr/commands/load.py
- stestr/tests/test_load.py
This commit fixes an edge case with the load command when there are no
test events in the subunit stream being passed to load. If the
pretty_out flag is set for the load command and there is no subunit
output the processing being used to handle the test run timing will fail
because there are no tests. This fixes that by just returning the test
run failed (because there were no sucessful tests run).
Fixes #244
> Fix edge case where there are no test times in output

- README.rst
This commit adds a note about the project's IRC channel to the README
file. The channel is very inactive and that's likely because no one
knows that it exists. It's good to have a place to ask a question about
the project in real time, so this commit adds a note about the channel
to advertise that it exists and is a place to discuss all things
stestr.
> Mention IRC channel in README

- .mailmap
This commit adds a mailmap file which can be used to deduplicate authors
or update email addresses in the git history. There were a couple of
duplicate entries in the git log for the project which was ending up in
the output authors list generated by PBR.
> Add mailmap file to deduplicate authors list

- setup.cfg
This commit fixes an oversight in the package metadata for stestr. We
were missing an explicit license field [1] in the package metadata. This
would lead to pip showing the license as unknown when inspecting the
stestr package.
[1] https://packaging.python.org/specifications/core-metadata/#license
> Add license to package metadata

- stestr/output.py
- stestr/tests/test_output.py
This commit makes unit tests in test_output.py use io.StringIO instead
of tempfile. It can reduce the code (no need seek(0)). And this commit
also fixes inconsistent code in output.py::output_tests() because it
caused an error with StringIO and it should be the same with the later
one.
The last thing is fixing the indentation in output_stream() which was
just weird.
> Use StringIO instead of tempfile

- doc/source/MANUAL.rst
- doc/source/internal_arch.rst
- setup.cfg
- stestr/commands/run.py
- stestr/config_file.py
- stestr/subunit_runner/program.py
- stestr/subunit_runner/run.py
- stestr/tests/test_config_file.py
Right now stestr doesn't actually own it's own test runner. It leverages
the subunit.run test runner, subunit.run in turn inherets from
testtools.run, which inherets from unittest2. The usage of unittest2
causes all sorts of problems when running non-testtools or non-unittest2
test suites, because of mismatches between stdlib unittest and unittest2.
To address this problem this commit creates a new test runner for stestr
that will emit subunit which is the actual only hard requirement for the
internal test runner used. This new test runner is more or less identical
to subunit.run, but instead of inheriting from testtools it uses stdlib
unittest directly.
Python 2.7's stdlib unittest's test runner is much older and it was
changed significantly for python 3. So building a custom test runner …
> Add custom test runner and remove testtools runner dependency

- stestr/commands/load.py
For some reason there are cases when a Nonetype object gets set as a
timestamp for a subunit result. Then when we go to analyze the total
test run in stestr load for subunit-trace output the min() or max()
calls to figure out the total test run duration it will fail because
python can't compare a Nonetype and a datetime.datetime. This commit
addresses this by ignoring cases where the a None is inserted.
> Handle NoneType timestamps in subunit results

- README.rst
- README_ja.rst
- doc/source/README_ja.rst
- doc/source/index.rst
This commit adds README_ja.rst which is a Japanese translation of
README.rst. This might be helpful to encourage to use stestr and to
participate development for Japanese.
> Add README_ja.rst

- stestr/subunit_runner/run.py
The stdlib python test runner introduced in #256 was written assuming a
python stdlib from python 3.5 or newer. Since we only officially support
running on python 3.5 or newer when we added the logic to switch between
the stdlib runner and the old testtools based runner we just said
python >=3.0.0. However, despite our official support status for
python >2.7,<3.5 there are still users out there running stestr on these python
versions. The new test runner will not work for those users because
unittest in stdlib changed in python 3.5 (as an aside this is the same
issue I've been hitting in my attempts to get unittest2 removed from
testtools). To address this problem a simple fix is to just change the
if statement to be a bit more explicit and only use the new runner for
python 3.5 or newer. …
> Only use stdlib based unittest runner for py >=3.5

- stestr/commands/run.py
This commit removes '-r' option which is an abbreviation for '--random'.
The option is conflicted with --repo-type/-r option and it doesn't work
properly. So, we can remove this now.
Fixes: #136
> Remove abbreviated option for stestr run --random

- doc/source/MANUAL.rst
In #267 we removed the short form for --random (-r) since this was
duplicated with --repo-type's short form (also -r). Since the 2.0.0
release which introduced cliff usage the -r option only worked for repo
type and would always error when trying to use it like --random. However
that PR neglected to remove a reference to the short form of --random in
the stestr manual. This commit corrects the oversight and removes the
reference.
> Remove stray reference to removed short form of --random

- stestr/subunit_trace.py
The attachments text in print_attachments() for the subunit_trace output
was encoding the text as utf8 for some reason which made the text of
type bytes. When bytes objects are printed by python 3 they're marked as
bytes by wrapping the text in b''. However this encode is unecessary (and
would likely break unicode characters) as just writing the str literals
for each line to the output stream works just fine. The encode() call was
added in [1] before stestr was started, and was just added for the case
of using LANG=C to set their locale to ASCII C. This was also before the
adoption of PEP 538 [2] which makes python use unicode even if LANG=C is
set. So removing the encode for supporting that use case shouldn't
matter anymore.
Fixes #243
[1] https://review.opendev.org/#/c/229527/
[2] …
> Stop encoding attachments text

- stestr/commands/init.py
- stestr/commands/load.py
- stestr/commands/run.py
- stestr/repository/file.py
- stestr/tests/repository/test_file.py
- stestr/tests/test_return_codes.py
This commit make an empty .stestr directory initialize if it exists.
Originally, we make it errors or weird errors occur when there is.
However, an empty .stestr directory can be initialized and no error
shouldn't be occurred with it.
Fixes: #266
> Handle empty .stestr directory to initialize

- stestr/repository/memory.py
- stestr/scheduler.py
- test-requirements.txt
This pulls in a newer pycodestyle/flake8 version which is a bit
more strict, so some fallout needs to be fixed.
> Update to recent hacking version

- .travis.yml
- azure-pipelines.yml
- setup.cfg
- tox.ini
Now that python 3.8 has been released we should add support for running
under it to stestr. This commit adds the required CI jobs to verify that
everything runs on 3.8 and also updates the package metadata to indicate
we support running on 3.8.
> Add Python 3.8 support

- stestr/cli.py
- stestr/config_file.py
- stestr/test_processor.py
/vpp/.tox/py36/lib/python3.6/site-packages/stestr/cli.py:39: DeprecationWarning: invalid escape sequence \.
group_regex = '([^\.]*\.)*' \
/vpp/.tox/py36/lib/python3.6/site-packages/stestr/config_file.py:130: DeprecationWarning: invalid escape sequence \.
group_regex = '([^\.]*\.)*'
/vpp/.tox/py36/lib/python3.6/site-packages/stestr/config_file.py:134: DeprecationWarning: invalid escape sequence \.
group_regex = '([^\.]*\.)*'
/vpp/.tox/py36/lib/python3.6/site-packages/stestr/test_processor.py:107: DeprecationWarning: invalid escape sequence \$
variable_regex = '\$(IDOPTION|IDFILE|IDLIST|LISTOPT)'
> Clean up DeprecationWarnings under python36

- azure-pipelines.yml
Python 3.8 support was added to stestr in #277, but at that time the
azure pipelines ci environment did not have support for python 3.8 in
the images. So CI for python 3.8 on Windows and macOS was not added at
that time because we use azure pipelines for that. However, python 3.8
has been added to the azure pipelines images now so this commit adds the
missing CI jobs to verify that everything works as expected on python
3.8 for windows and macOS users.
Fixes #280
> Add python 3.8 macOS and windows ci jobs

- requirements.txt
This version includes an important Python 3 fix [1], without which a Python 3-only stestr doesn't really make sense.
[1] https://github.com/testing-cabal/subunit/pull/40
> Bump python-subunit minimum to 1.4.0

- .travis.yml
Now that we've dropped support for python 2.7 from stestr we're no
longer advertising or building universal wheels. However we never
updated the travis job which publishes the release to pypi to drop the
--universal flag when it builds the wheel for release. This commit
corrects the oversight so that in future releases we don't try to build
a universal wheel.
> Remove universal flag from release job

- setup.cfg
Here is the doc with right name -
https://packaging.python.org/guides/distributing-packages-using-setuptools/#python-requires
> use python-requires metadata instead of requires-python

- stestr/scheduler.py
- test-requirements.txt
- tox.ini
The hacking version being used in stestr was quite old, being
released >2 years ago, and didn't work with python 3.8. This commit bumps
to the latest version to pull in newer versions of all the linters and updates
the formatting to fix new checks.
> Bump hacking version

- doc/source/MANUAL.rst
- stestr/commands/list.py
- stestr/commands/run.py
- stestr/config_file.py
- stestr/selection.py
- stestr/test_processor.py
- stestr/tests/test_config_file.py
- stestr/tests/test_return_codes.py
- stestr/tests/test_selection.py
Added the new option while posting a Deprecation Warning for the old one.
The old option will be supported for now but it is soon to be retired...
So for now, both options are equally usable and will have the same effect.
Tests relying on the old option are kept intact, will be removed only when
the option itself is removed. New tests are added to verify that the same
behaviour is afforded if the new option is used also.
Closes #296
> Change option '--whitelist-file' to '--include-list'

- .travis.yml
- azure-pipelines.yml
- setup.cfg
This commit adds Python 3.9 support to stestr. It adds Python 3.9 as
supported python version in the trove classifiers for the package
metadata and adds CI jobs that test stestr on python 3.9.
> Add python 3.9 support

- stestr/subunit_trace.py
- stestr/tests/test_subunit_trace.py
In some situations (especially when testing compiled extensions) a test
case can trigger a segfault or some other scenario that crashes python.
When this occurs the worker doesn't send back the second subunit event
that reports the test status and that leaves the test case stuck as
inprogress. This becomes tricky to debug as there is no clear message as
to why the test run failed. While we were correctly not returning a 0
return code in this situation there was no error message about why we
didn't. This commit fixes this oversight by adding a check to the end of
subunit-trace so that we report any tests with an inprogress state and
explain that we're failing because they likely crashed python.
> Report tests stuck as inprogress as failures

- .github/workflows/main.yml
- README.rst
- README_ja.rst
The stestr default branch has been renamed from 'master' to 'main'. To
ensure we're actually running CI and links work this commit updates some
dangling references left in the repository to the previous default
branch name.
> Update CI for renamed default branch

- setup.cfg
In recent version of setuptools installing stestr has started raising
deprecation warnings about some of the metadata fields we were setting.
This commit updates the setup.cfg to use the names that are not
deprecated to fix the warnings and avoid having issues with a future
release of setuptools when the fields are removed.
> Update package metadata field names

- .github/workflows/main.yml
- doc/source/MANUAL.rst
- stestr/cli.py
- stestr/commands/init.py
- stestr/repository/sql.py
- stestr/repository/util.py
- stestr/tests/repository/test_sql.py
- test-requirements.txt
- tox.ini
This commit deprecates the sql repository type for future removal in the
next major version release (4.0.0). Included in this deprecation is the
`--repo-type`argument which only makes sense with >1 repository type. The
sql repository type depends on the subunit2sql project which is not
really active anymore. It never managed to reach feature parity with the
default file repository type and has been listed as experimental it's
whole existence. At this point it's realistically never going to replace
the file repository which was the original long term plan. One note is
that we both emit a `DeprecationWarning` and print a warning to stderr
when the sql repository type is set. This is because in my local testing
the `DeprecationWarning` was not actually show to the user, but I left it
in …
> Deprecate the sql repository type

- doc/source/MANUAL.rst
- requirements.txt
- setup.cfg
- stestr/commands/__init__.py
- stestr/commands/history.py
- stestr/repository/abstract.py
- stestr/repository/file.py
- stestr/repository/memory.py
- stestr/repository/sql.py
- stestr/subunit_trace.py
- stestr/tests/repository/test_file.py
- stestr/tests/repository/test_sql.py
- stestr/tests/test_return_codes.py
- stestr/tests/test_user_config.py
- stestr/user_config.py
This commit adds a new command to stestr, history. The history command
is used for interacting with the history of results in the repository.
Prior to this commit you could only interact with the most recent run in
the repository via the last command, but anything older was just taking
up disk space and never used. The history command to start has 3
subcommands, 'list', 'show', and 'remove'. List will generate a table of
all the contents of the repository that will show the run id, the result
of the run, when it started, how long it took, and optionally show any
metadata for the run. Show will show a run in the repository, this is
equivalent to 'stestr last', but takes an optional run id instead of just
unconditionally showing the last run. Remove is used to remove runs from
the …
> Add history commands to stestr

- stestr/subunit_trace.py
- stestr/tests/test_subunit_trace.py
In #304 we attempted to add an error message when a test fails prior to
reporting its final status (like in case of a segfault). However, that
PR didn't work as intended because the condition to check if there were
any tests inprogress was incorrect. It relied on the count_tests()
function in subunit_trace which was returning zero as it was called
there even when tests were left in the inprogress state. However, this
call wasn't actually needed because we call get_stuck_in_progress()
right before the condition which collects any test ids from the subunit
stream that are left inprogress. This commit fixes the issue by just
checking that the output list from get_stuck_in_progress() has entries.
Then to ensure this doesn't regress in the future the unittest added in
PR #304 is updated to …
> Fix inprogress test detection

- doc/source/MANUAL.rst
- stestr/commands/list.py
- stestr/commands/load.py
- stestr/commands/run.py
- stestr/config_file.py
- stestr/selection.py
- stestr/test_processor.py
- stestr/tests/test_config_file.py
- stestr/tests/test_return_codes.py
- stestr/tests/test_selection.py
In preparation for the stestr 4.0.0 release this commit removes the
deprecated command line options. This includes '--whitelist-file',
'--blacklist-file', '--black-regex' and '--partial'. The selection
options have been deprecated for > 1 year and the '--partial' option has
been deprecated > 4 years and hasn't had any effect in that time. The
4.0.0 release will be primarily to make these deprecation removals
(along with the sql repository type which will be in a separate commit).
> Remove deprecated command line flags

- .github/workflows/main.yml
- setup.cfg
- stestr/tests/files/tox.ini
- tox.ini
This commit adds Python 3.10 support and drop 3.5 at the same time. We
should support the latest release version as possible. And, we can drop
the 3.5 because the version is already EOL for more than 1.5 years[1].
[1] https://www.python.org/downloads/release/python-3510/
> Add Python 3.10 support and drop 3.5

- stestr/commands/failing.py
- stestr/commands/history.py
- stestr/commands/init.py
- stestr/commands/last.py
- stestr/commands/load.py
- stestr/commands/run.py
- stestr/commands/slowest.py
- stestr/config_file.py
- stestr/repository/util.py
- stestr/tests/test_config_file.py
This commit deprecates `repo_type` parameter in `get_repo_open` and
`get_repo_initialise` functions. As we discussed in PR#318 [1], these
should be deprecated before 4.0.0 release.
[1] https://github.com/mtreinish/stestr/pull/318
> Deprecate repo_type parameter in get_repo_open and get_repo_initialise

- stestr/output.py
This commit adds a destructor to wait for a process termination in
`ReturnCodeToSubunit` class. This commit fixes #320 partially.
> Add destructor to wait for process termination

- README.rst
We migrated the stestr IRC channel off of Freenode some time ago but
never updated the README to reflect it now lives in OFTC. This commit
corrects this oversight so people who are interested in joining the
channel will be able to find it.
> Update IRC network for stestr channel

- .github/workflows/main.yml
- tox.ini
This commit adds coverxml task to tox.ini and cover job to main.yml to
enable coverage tracking. We already have it in travis.yml but it seems
it hasn't worked recently. And, it's a good timing to migrate to GitHub
Actions if it works well because we can remove travis.yml just only for
tracking the coverage.
> Add coverxml task and cover job

- stestr/utils.py
This commit removes CallWhenProcFinishes class in utils.py, its usage
was removed in the commit[1].
[1] 182c6acda970088ea36d0252ce2fd08844b3b02d
> Remove CallWhenProcFinishes class in utils.py

- stestr/commands/run.py
- stestr/selection.py
- stestr/subunit_runner/program.py
- stestr/test_processor.py
- stestr/tests/subunit_runner/test_program.py
- stestr/tests/test_load.py
- stestr/tests/test_run.py
- stestr/tests/test_selection.py
When using `--load-list` to run tests the tests were always run in a different order than the one provided in the file, even when the `--random` argument was not present:
```
$ stestr run --serial --load-list failing
```
This patch preserves the order of the tests from the file when `--load-list` is used, and it will only randomize it when `--random` is provided:
```
$ stestr run --serial --random --load-list failing
```
> Fix #330 - Preserve load-list order

- stestr/commands/load.py
- stestr/subunit_trace.py
Previously `stestr run` and subunit_trace used slightly different output and validation logic. run wouldn't catch the case where a test exited without a status, while code using `last` and `history` would since they used subunit_trace.
Refactor the subunit_trace output and validation logic and use it for `load`/`run`.
Converge on the subunit_trace formatted output, in addition to the summary also show if something goes wrong.
The primary motivation for this change is to better detect when a subprocess is killed and not all tests are run as expected (segfault, OOM etc.).
> Reuse subunit_trace output/validation logic for load/run

- stestr/commands/load.py
- stestr/subunit_trace.py
Previously `stestr run` and subunit_trace used slightly different output and validation logic. run wouldn't catch the case where a test exited without a status, while code using `last` and `history` would since they used subunit_trace.
Refactor the subunit_trace output and validation logic and use it for `load`/`run`.
Converge on the subunit_trace formatted output, in addition to the summary also show if something goes wrong.
The primary motivation for this change is to better detect when a subprocess is killed and not all tests are run as expected (segfault, OOM etc.).
Backported from #333
> Reuse subunit_trace output logic for load/run

- .github/workflows/main.yml
- requirements.txt
- setup.cfg
- stestr/repository/file.py
- tox.ini
This package appears to be a holdover from dropping Python 2.x support, and is no longer needed.
This resolves https://nvd.nist.gov/vuln/detail/CVE-2022-40899
Also update tox.ini to work wirth modern vintages of tox.
> Remove vestigial future package from requirements

- test-requirements.txt
Black only provides backwards compatibility guarantees for each year's versions. The major version is the year which will not make any breaking format changes in that release. Since we're in 2023 now black has released a 23.x.y release which causes incompatible changes with our previously used 22.x.y version. In the short term to avoid failures caused by these unrelated changes this commit pins our version to 22.x.y. In the future we can upgrade this version and update the formatting with the new rules at that time.
> Pin black to 2022 version

- doc/source/MANUAL.rst
- requirements.txt
- stestr/commands/list.py
- stestr/commands/run.py
- stestr/config_file.py
- stestr/tests/test_config_file.py
- Lightly refactor `config_file.TestrConf` to improve code reuse, and make it easier to invoke and use
- Add/update tests where needed
- Update documentation
Closes #340
> Add support for storing stestr configs in pyproject.toml

- stestr/subunit_runner/program.py
> Adding another prefix to the existing list of unittest_import_strs

- tox.ini
The docs builds were previously configured to use PBR's sphinx entrypoint. However, in newer versions of PBR that no longer exists and the docs builds are failing. This commit updates the tox job to just directly call sphinx-build to fix the docs builds locally and in CI.
> Update docs job to avoid setup.py entrypoint

- stestr/commands/run.py
See https://docs.python.org/3.12/whatsnew/3.12.html#removed
> Replace removed SafeConfigParser with ConfigParser

- requirements.txt
- stestr/tests/test_subunit_trace.py
- test-requirements.txt
it is imported after all..
Closes #347
> Explicitly list extras as dependency

- codecov.yml
The coverage reporting via codecov was only meant to be informational but it is now reporting CI failures in the checks table when coverage changes. This is exceedingly noisy and while we've just been ignoring it so far, removing the red X from the UI would be nice. This commit adds a codecov configuration file that explicitly lists the configuration as informational only.
> Disable checks failure on coverage

- .github/workflows/release.yml
This commit updates the wheel job CI configuration to leverage PyPI's trusted publisher mechanism. Moving forward the bot account we've been using will be deleted (as it will require 2fa) and the stestr github repository's release workflow has been setup as a trusted publisher. This commit updates the job configuration per:
https://docs.pypi.org/trusted-publishers/using-a-publisher/
to autheticate the job directly against pypi for publishing the package files without needing any user credentials.
> Pivot PyPI publishing to use trusted publishers

- setup.cfg
This commit updates the stestr package metadata to reflect that Python 3.12 is supported now. The previous release 4.1.0 had preliminary support for 3.12, but was blocked on our upstream dependencies needing fixes for running with 3.12 to run it in CI. This commit updates the pacakge metadata so the trove classifiers indicate that Python 3.12 is now a supported version of Python. The other thing being updated is the minimum version of Python supported in the metadata (which results in a pip error if an older version is trying to install the package) is set to 3.7, it was previously set to 3.6 but we dropped 3.6 support in: 9d5a504 which was part of the 4.1.0 release.
> Update package metadata for support Python versions

- .github/workflows/main.yml
- setup.cfg
- tox.ini
Python 3.7 already reached its EOL on 2023-06-27[1].
[1] https://devguide.python.org/versions/
> Remove Python 3.7 support

- .github/workflows/main.yml
This commit bumps the codecov action version. We were previously using v3 which no longer is supported and can't be used anymore. This upgrades the action to use the latest version v5.
> Bump codecov action version

- stestr/commands/run.py
- stestr/tests/test_return_codes.py
- tox.ini
> Normalize paths

- .github/workflows/main.yml
- tox.ini
It seems tox 4 does not install console scripts wen skipsdist = True is set. This removes the option so that we can use the stestr command in tests.
Also, the allowlist_externals option was added in tox 3.18.0 so the minimum version should be fixed accordingly.
> Adapt to tox 4

- .github/workflows/main.yml
- .github/workflows/release.yml
The docs ci (and the release if that were triggered) job is failing right now because it is using the non-existent upload-artifact v3 action. To fix this issue this commit updates it to the latest version.
> Update upload-artifact action in CI

- .github/workflows/release.yml
In #373 we modernized the packaging infrastructure for stestr and no longer contain a setup.py. However this PR forgot to update the release job to update how we build the artifacts for PyPI. This commit refactors the workflow to use build to create the artifacts.
> Update release job to work with new packaging structure
